[build-system]
requires = ["setuptools >= 65.5.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Team-15-AWN_AI"
dynamic = ["version"]
requires-python = ">= 3.12"
authors = [ # put your name, email here!
    {name = "Gavin Travis", email = "gavin.travis@wsu.edu"},
    {name = "Sairaghav Gubba", email = "sairaghav.gubba@wsu.edu"},
    {name = "Danbi Kim", email = "danbi.kim1@wsu.edu"},
    {name = "Zuriel Hernandez", email = "z.hernandezguerra@wsu.edu"},
]
dependencies = [
    "python-dotenv",
    "mysql-connector-python",
    "psycopg[binary]",
    "langchain"
]

[project.optional-dependencies]
dev = [
    "pre-commit",
    "ruff",
    "black",
    "isort",
    "pyright",
    "pytest",
]

[tool.setuptools.packages.find]
where = ["code"]

[tool.black]
line-length = 120

[tool.ruff]
line-length = 120 # max line length
exclude = [".venv", "*.md", ".egg*", ".git", ".gitignore"] # stuff not to lint + format

[tool.ruff.lint]
select = [
    "E", # code style errs
    "W", # code style warnings
    "F", # pyflakes issues -> fancy set of rules
    "D", # doc string rules
    "N", # pep8 naming conventions
    "B", # bugbear errs -> more fancy rules
    "I", # isort compatibility
]

ignore = [
    #"put err code here", # ignore specific err codes here, only do if its very unreasonable!
    "D203", # Conflict: One-blank-line-before-class (Incompatible with D211)
    "D213", # Conflict: Multi-line-summary-second-line (Incompatible with D212)
]

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.pytest.ini_options]
minversion = "9.0.2"
addopts = "-q" # flags to pass to pytest implicitly
testpaths = [ # the directories pytest will search for tests per test discover rules
    "testing",
]
